sonlar=[1,2,3,4,5,6]
print(sonlar)
# sonlar.append([3,2,6,5])
# print(sonlar)
# print(sonlar[3][-3:])
# print(len(sonlar))
# sonlar.extend([3,5,8,"dgdfg"])
# print(sonlar)
# sonlar.insert(1,256)
# print(sonlar)
# sonlar.remove(125)
# print(sonlar)
# sonlar.pop(1)
# print(sonlar)
# sonlar.sort()
# print(sonlar)
# sonlar.reverse()
# print(sonlar)
# sonlar.clear()
# print(sonlar)
for i in range(0,len(sonlar)):
   print(f"Bu listda {sonlar[i]} raqamlari bor")