# bu masalada ham muammo bor, oxiriga yetmagan
xona=int(input("Necha xonali son kritmoqchisiz: "))
son=int(input("Sonni kiriting: "))
while son!=0:
   if xona==2:
      son=son//10
      if son==1:
         print("bir ")
      elif son==2:
         print("ikki ")
      elif son==3:
         print("uch ")
      elif son==4:
         print("to'rt ")
      elif son==5:
         print("besh ")
      elif son==6:
         print("olti ")
      elif son==7:
         print("yetti ")
      elif son==8:
         print("sakkiz ")
      elif son==9:
         print("to'qqiz ")
      elif son==10:
         print("o'n ")
      elif son==20:
         print("yigirma ")
      elif son==30:
         print("o'ttiz ")
      elif son==40:
         print("qirq ")
      elif son==50:
         print("ellik ")
      elif son==60:
         print("oltmish ")
      elif son==70:
         print("yetmish ")
      elif son==80:
         print("sakson ")
      elif son==90:
         print("to'qson ")
      elif son==100:
         print("yuz ")
   elif xona==3:
      son=son//10
      if son==1:
         print("bir ")
      elif son==2:
         print("ikki ")
      elif son==3:
         print("uch ")
      elif son==4:
         print("to'rt ")
      elif son==5:
         print("besh ")
      elif son==6:
         print("olti ")
      elif son==7:
         print("yetti ")
      elif son==8:
         print("sakkiz ")
      elif son==9:
         print("to'qqiz ")
      elif son==10:
         print("o'n ")
      elif son==20:
         print("yigirma ")
      elif son==30:
         print("o'ttiz ")
      elif son==40:
         print("qirq ")
      elif son==50:
         print("ellik ")
      elif son==60:
         print("oltmish ")
      elif son==70:
         print("yetmish ")
      elif son==80:
         print("sakson ")
      elif son==90:
         print("to'qson ")
      elif son==100:
         print("yuz ")